export const typeObj: Record<string, { enName: string; chName: string }[]> = {
  冒险家: [
    { enName: "Hero", chName: "英雄" },
    { enName: "Paladin", chName: "圣骑士" },
    { enName: "Dark Knight", chName: "黑骑士" },
    { enName: "Fire, Poison", chName: "火毒" },
    { enName: "Ice, Lightning", chName: "冰雷" },
    { enName: "Bishop", chName: "主教" },
    { enName: "Bowmaster", chName: "神射手" },
    { enName: "Marksman", chName: "箭神" },
    { enName: "Pathfinder", chName: "古迹猎人" },
    { enName: "Night Lord", chName: "隐士" },
    { enName: "Shadower", chName: "侠盗" },
    { enName: "Dual Blade", chName: "暗影双刀" },
    { enName: "Buccaneer", chName: "冲锋队长" },
    { enName: "Corsair", chName: "船长" },
    { enName: "Cannoneer", chName: "神炮王" },
    { enName: "Jett", chName: "杰特" },
  ],
  反抗者: [
    { enName: "Blaster", chName: "爆破手" },
    { enName: "Battle Mage", chName: "唤灵斗师" },
    { enName: "Wild Hunter", chName: "弩豹游侠" },
    { enName: "Mechanic", chName: "机械师" },
    { enName: "Demon Slayer", chName: "恶魔猎手" },
    { enName: "Demon Avenger", chName: "恶魔复仇者" },
    { enName: "Xenon", chName: "尖兵" },
  ],
  希纳斯骑士团: [
    { enName: "Mihile", chName: "米哈尔" },
    { enName: "Dawn Warrior", chName: "魂骑士" },
    { enName: "Blaze Wizard", chName: "炎术士" },
    { enName: "Wind Archer", chName: "风灵使者" },
    { enName: "Night Walker", chName: "夜行者" },
    { enName: "Thunder Breaker", chName: "奇袭者" },
  ],
  冒险岛英雄: [
    { enName: "Aran", chName: "战神" },
    { enName: "Evan", chName: "龙神" },
    { enName: "Mercedes", chName: "双弩精灵" },
    { enName: "Phantom", chName: "幻影" },
    { enName: "Luminous", chName: "夜光法师" },
    { enName: "Shade", chName: "隐月" },
  ],
  诺巴族: [
    { enName: "Kaiser", chName: "狂龙战士" },
    { enName: "Kain", chName: "炼狱黑客" },
    { enName: "Cadena", chName: "魔链影士" },
    { enName: "Angelic Buster", chName: "爆莉萌天使" },
  ],
  翼人族: [
    { enName: "Adele", chName: "御剑骑士" },
    { enName: "Illium", chName: "圣晶使徒" },
    { enName: "Khali", chName: "飞刃沙士" },
    { enName: "Ark", chName: "影魂异人" },
  ],
  晓之阵: [
    { enName: "Hayato", chName: "剑豪" },
    { enName: "Kanna", chName: "阴阳师" },
  ],
  阿尼玛: [
    { enName: "Lara", chName: "元素师" },
    { enName: "Hoyoung", chName: "虎影" },
  ],
  其他: [
    { enName: "Beast Tamer", chName: "林之灵" },
    { enName: "Zero", chName: "神之子" },
    { enName: "Kinesis", chName: "超能力者" },
    { enName: "Mo Xuan", chName: "墨玄" },
  ],
};

export const picObj: Record<string, string> = {
  Hero: "https://i.imgur.com/1ulnMH2.png",
  Paladin: "https://i.imgur.com/vVhcVdt.png",
  "Dark Knight": "https://i.imgur.com/k3H59GT.png",
  "Fire, Poison": "https://i.imgur.com/h7k1JgT.png",
  "Ice, Lightning": "https://i.imgur.com/CRSiEzP.png",
  Bishop: "https://i.imgur.com/MZFCKgQ.png",
  Bowmaster: "https://i.imgur.com/XnFSqtX.png",
  Marksman: "https://i.imgur.com/pDTDdtb.png",
  Pathfinder: "https://i.imgur.com/AcXfK3s.png",
  "Night Lord": "https://i.imgur.com/Eabrj2Q.png",
  Shadower: "https://i.imgur.com/tdHm6PQ.png",
  "Dual Blade": "https://i.imgur.com/SiQnfLf.png",
  Buccaneer: "https://i.imgur.com/KfLp3Re.png",
  Corsair: "https://i.imgur.com/sgiVArv.png",
  Cannoneer: "https://i.imgur.com/PAt7PZw.png",
  Jett: "https://i.imgur.com/0kokwak.png",
  "Dawn Warrior": "https://i.imgur.com/GzfOnna.png",
  "Blaze Wizard": "https://i.imgur.com/OtcXs5a.png",
  "Wind Archer": "https://i.imgur.com/Y14H8Xe.png",
  "Night Walker": "https://i.imgur.com/3ZdEMb8.png",
  "Thunder Breaker": "https://i.imgur.com/Bp2qjay.png",
  Mihile: "https://i.imgur.com/eWwYTvn.png",
  Aran: "https://i.imgur.com/C0OTSbz.png",
  Evan: "https://i.imgur.com/46sISwn.png",
  Mercedes: "https://i.imgur.com/O9qmvng.png",
  Phantom: "https://i.imgur.com/Vl53eUY.png",
  Luminous: "https://i.imgur.com/lYr1k1j.png",
  Shade: "https://i.imgur.com/lb4uBMS.png",
  Blaster: "https://i.imgur.com/ssgVbSx.png",
  "Battle Mage": "https://i.imgur.com/cxVBV52.png",
  "Wild Hunter": "https://i.imgur.com/MDls3MJ.png",
  Mechanic: "https://i.imgur.com/1RizClQ.png",
  "Demon Slayer": "https://i.imgur.com/bIJuGqM.png",
  "Demon Avenger": "https://i.imgur.com/i85U7Xc.png",
  Xenon: "https://i.imgur.com/hO0swBz.png",
  Kaiser: "https://i.imgur.com/nghL0r9.png",
  Kain: "https://i.imgur.com/2b11nee.png",
  Cadena: "https://i.imgur.com/DeqKv9j.png",
  "Angelic Buster": "https://i.imgur.com/CJl63Xc.png",
  Adele: "https://i.imgur.com/7vuZxzh.png",
  Illium: "https://i.imgur.com/JMTn1D9.png",
  Khali: "https://i.imgur.com/uvrDPwj.png",
  Ark: "https://i.imgur.com/GWZQfcz.png",
  Hayato: "https://i.imgur.com/HlElG6z.png",
  Kanna: "https://i.imgur.com/pb3PZ03.png",
  Lara: "https://i.imgur.com/iHpj5PU.png",
  Hoyoung: "https://i.imgur.com/5c1WC61.png",
  "Beast Tamer": "https://i.imgur.com/RP77CZ1.png",
  Zero: "https://i.imgur.com/JAeSKjo.png",
  Kinesis: "https://i.imgur.com/8n4cOR8.png",
  "Mo Xuan": "https://i.imgur.com/YoErUGN.png",
};
