export const typeObj: Record<string, { enName: string; chName: string }[]> = {
  冒险家: [
    { enName: "Hero", chName: "英雄" },
    { enName: "Paladin", chName: "圣骑士" },
    { enName: "Dark Knight", chName: "黑骑士" },
    { enName: "Magician (Fire, Poison)", chName: "火毒魔导师" },
    { enName: "Magician (Ice, Lightning)", chName: "冰雷魔导师" },
    { enName: "Bishop", chName: "主教" },
    { enName: "Bowmaster", chName: "神射手" },
    { enName: "Marksman", chName: "箭神" },
    { enName: "Pathfinder", chName: "古迹猎人" },
    { enName: "Night Lord", chName: "隐士" },
    { enName: "Shadower", chName: "侠盗" },
    { enName: "Dual Blade", chName: "暗影双刀" },
    { enName: "Buccaneer", chName: "冲锋队长" },
    { enName: "Corsair", chName: "船长" },
    { enName: "Cannoneer", chName: "神炮王" },
    { enName: "Jett", chName: "杰特" },
  ],
  反抗者: [
    { enName: "Blaster", chName: "爆破手" },
    { enName: "Battle Mage", chName: "唤灵斗师" },
    { enName: "Wild Hunter", chName: "弩豹游侠" },
    { enName: "Mechanic", chName: "机械师" },
    { enName: "Demon Slayer", chName: "恶魔猎手" },
    { enName: "Demon Avenger", chName: "恶魔复仇者" },
    { enName: "Xenon", chName: "尖兵" },
  ],
  希纳斯骑士团: [
    { enName: "Mihile", chName: "米哈尔" },
    { enName: "Dawn Warrior", chName: "魂骑士" },
    { enName: "Blaze Wizard", chName: "炎术士" },
    { enName: "Wind Archer", chName: "风灵使者" },
    { enName: "Night Walker", chName: "奇袭者" },
    { enName: "Thunder Breaker", chName: "杰特" },
  ],
  冒险岛英雄: [
    { enName: "Aran", chName: "战神" },
    { enName: "Evan", chName: "龙神" },
    { enName: "Mercedes", chName: "双弩精灵" },
    { enName: "Phantom", chName: "幻影" },
    { enName: "Luminous", chName: "夜光法师" },
    { enName: "Shade", chName: "隐月" },
  ],
  诺巴族: [
    { enName: "Kaiser", chName: "狂龙战士" },
    { enName: "Kain", chName: "炼狱黑客" },
    { enName: "Cadena", chName: "魔链影士" },
    { enName: "Angelic Buster", chName: "爆莉萌天使" },
  ],
  翼人族: [
    { enName: "Adele", chName: "御剑骑士" },
    { enName: "Illium", chName: "圣晶使徒" },
    { enName: "Khali", chName: "飞刃沙士" },
    { enName: "Ark", chName: "影魂异人" },
  ],
  晓之阵: [
    { enName: "Hayato", chName: "剑豪" },
    { enName: "Kanna", chName: "阴阳师" },
  ],
  阿尼玛: [
    { enName: "Lara", chName: "元素师" },
    { enName: "Hoyoung", chName: "虎影" },
  ],
  其他: [
    { enName: "Beast Tamer", chName: "林之灵" },
    { enName: "Zero", chName: "神之子" },
    { enName: "Kinesis", chName: "超能力者" },
    { enName: "Mo Xuan", chName: "墨玄" },
  ],
};
